import Bullet from '@/app/_components/bullet'
import Tab from '@/app/_components/tab'
import Row from '@/app/_components/row'
import { Table } from '@/app/_components/table'
import { Paragraph } from '@/app/_components/paragraph'

export function shortDesc() {
  return (
    <div className='text-amber'>
      <b>Computer Fan Silencer</b>
      <br/>Supports 12V and 5V PWM Fans
      <br/>Maximum load current 1A
    </div>
  )
}

export function longDesc() {
  return (
    <div className='text-amber'>
      <b>Suppresses electrical noise</b> generated by the fan's motor. All wires are filtered: Power feed and two Control lines (PWM and Tacho)
      <br/><b>Adjustable Fan Speed</b>: Regulates maximum voltage supplied to the fan, best suited for 12V (this option can be turned off with a jumper)
      <br/><b>Protected</b> from overvoltage, short-circuit, and overcurrent failure modes with an auto-resettable fuse
    </div>
  )
}

export function specs() {
  return (
    <div className='text-amber'>
      <Table rows={4} cols={2}>
        <div className='w-[100px]'><b>Weight</b></div>
        <div><i>0.055 kg</i></div>
        <div><b>Dimensions</b></div>
        <div><i>12 x 5 x 2 cm</i></div>
        <div><b>Amperage</b></div>
        <div><i>1A</i></div>
        <div><b>Voltage</b></div>
        <div><i>5V, 12V</i></div>
      </Table>
    </div>
  )
}